{{ range $rsName, $rs := .Values.remoteStorages }}
{{ range $replica := until ($.Values.writeReplicas | default 1 | int) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-vmagent-data-{{ $rsName }}-replica-{{ $replica }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" $ | nindent 4 }}
spec:
  storageClassName: premium-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
{{ end }}
{{ end }}
