kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "prometheus-benchmark.fullname" . }}-vmsingle-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
