apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "prometheus-benchmark.fullname" . }}-vmsingle-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" . | nindent 4 }}
data:
  scrape.yml: |
    global:
      scrape_interval: {{ .Values.scrapeInterval }}
    scrape_configs:
{{- range $replica := until ($.Values.writeReplicas | default 1 | int) }}
    - job_name: http-sd-{{ $replica }}
      http_sd_configs:
      - url: http://{{ include "prometheus-benchmark.fullname" $ }}-http-sd-replica-{{ $replica }}:8436
{{- end }}
