{{ range $replica := until ($.Values.writeReplicas | default 1 | int) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-http-sd-replica-{{ $replica }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      job: http-sd
      replica: {{ $replica }}
      {{- include "prometheus-benchmark.selectorLabels" $ | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/nginx-cm: {{ include (print $.Template.BasePath "/http-sd/nginx-cm.yaml") $ | sha256sum }}
      labels:
        job: http-sd
        replica: {{ $replica }}
        {{- include "prometheus-benchmark.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: http-sd
        image: "victoriametrics/vmagent-config-updater:heads-scrape-benchmark-0-gfab269c"
        args:
        - --httpListenAddr=:8436
        - --configMode=http_sd_config
        - --targetsCount={{ $.Values.targetsCount }}
        - --targetAddr={{ include "prometheus-benchmark.fullname" $ }}-http-sd-replica-{{ $replica }}:9102
        - --scrapeInterval={{ $.Values.scrapeInterval }}
        - --scrapeConfigUpdatePercent={{ $.Values.scrapeConfigUpdatePercent }}
        - --scrapeConfigUpdateInterval={{ $.Values.scrapeConfigUpdateInterval }}
        ports:
          - containerPort: 8436
            name: http-sd    
      - name: nodeexporter
        image: prom/node-exporter:v1.6.1
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          - --path.rootfs=/host/root
          - --no-collector.wifi
          - --no-collector.hwmon
          - --no-collector.time
          - --no-collector.timex
          - --no-collector.arp
          - --no-collector.netdev
          - --no-collector.netstat
          - --collector.processes
          - --web.max-requests=40
          - --web.listen-address=:9101
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: sys
            mountPath: /host/sys
            readOnly: true
          - name: root
            mountPath: /host/root
            mountPropagation: HostToContainer
            readOnly: true
        ports:
          - containerPort: 9101
            name: metrics
      - name: nginx
        image: nginx:1.23.1
        args:
          - nginx
          - -c
          - /opt/nginx/nginx.conf
        ports:
          - containerPort: 9102
            name: nginx
        volumeMounts:
          - mountPath: /opt/nginx
            name: nginx-cm
          - mountPath: /tmp/nginx
            name: nginx-cache
          - mountPath: /etc/nginx
            name: nginx-empty
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-cm
        configMap:
          name: {{ include "prometheus-benchmark.fullname" $ }}-nginx-cm
      - name: nginx-empty
        emptyDir: {}
---
{{ end }}
