{{ range $replica := until ($.Values.writeReplicas | default 1 | int) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-http-sd-replica-{{ $replica }}
spec:
  selector:
    job: http-sd
    replica: {{ $replica | quote }}
    {{- include "prometheus-benchmark.selectorLabels" $ | nindent 4 }}
  clusterIP: None
  ports:
  - name: nginx
    port: 9102
  - name: http-sd
    port: 8432
---
{{ end }}
