apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-benchmark.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    job: monitoring
    {{- include "prometheus-benchmark.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      job: monitoring
      {{- include "prometheus-benchmark.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/monitoring-cm: {{ include (print .Template.BasePath "/monitoring/monitoring-cm.yaml") . | sha256sum }}
      labels:
        job: monitoring
        {{- include "prometheus-benchmark.labels" . | nindent 8 }}
    spec:
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "prometheus-benchmark.fullname" . }}-monitoring
      containers:
      - name: vmsingle
        image: "victoriametrics/victoria-metrics:{{ .Values.vmtag }}"
        args:
        - --httpListenAddr=:8428
        - --promscrape.config=/config/scrape.yml
        - --storageDataPath=/data
        - --promscrape.kubernetesSDCheckInterval=5s
        ports:
        - name: metrics
          containerPort: 8428
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: {{ include "prometheus-benchmark.fullname" . }}-monitoring-cm
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "prometheus-benchmark.fullname" . }}-monitoring-data
